version: '3.7'

services:
  # App backend service
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carangobom
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
      JWT_SECRET: 9ac7ff63ea6f3d3607d20f6f4e900547
      DATABASE_DRIVER: org.postgresql.Driver
    networks:
      - backend
      - frontend
  # Frontend Service
  web:
    build:
      context: web
      dockerfile: Dockerfile
      args:
        API_BASE: http://localhost:8080
        PORT: 80
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - api
    networks:
      - frontend

  # Database Service (postgres)
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'carangobom'
      POSTGRES_USER: 'root'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/database
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend: