version: '3.7'

services:
  # App backend service
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/carangobom
      DATABASE_USER: root
      DATABASE_PASSWORD:
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
      JWT_SECRET: 9ac7ff63ea6f3d3607d20f6f4e900547
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
    networks:
      - backend
      - frontend
  # Frontend Service
  web:
    build:
      context: web
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - api
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'carangobom'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend: