name: Deploy Frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: clean npm install
        working-directory: ./front
        run: npm ci
      - name: Install Jest
        working-directory: ./front
        run: sudo npm i -g jest
      - name: Run Tests
        working-directory: ./front
        run: npm test
      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@master
        working-directory: ./front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build
        working-directory: ./front
        run: npm build
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-files-front
          path: ./front/dist/
  deploy:
    runs-on: ubuntu-latest
    environment: 'develop'
    needs:
      - build
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-files-front
